steps:
  # Build the container image from the api directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/moodcoach:$COMMIT_SHA'
      - './api'
    timeout: '1800s'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/moodcoach:$COMMIT_SHA'

  # Delete existing service to start fresh
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'delete'
      - 'moodcoach'
      - '--region'
      - 'us-central1'
      - '--quiet'
    id: 'delete-service'

  # Deploy container image to Cloud Run (fresh service)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'moodcoach'
      - '--image'
      - 'gcr.io/$PROJECT_ID/moodcoach:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '1'
      - '--allow-unauthenticated'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'USE_FINETUNED=false,FINETUNED_MODEL_PATH=emotion_model/,API_PORT=8080'
    id: 'deploy-service'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'